### ISSUE TITLE
Can we have a talk on your article?

### ISSUE THREAD

**Issue by trcrsired** [depp/vadpcm#14]
I agree iostream is hopelessly broken. but i disagree fmt is not a solution. Please do not recommend it.

https://www.moria.us/articles/iostream-is-hopelessly-broken/

1. Your example of gettext does not work on C++20 format because C++ forces format string to be a compile time one now.
2. Runtime format string creates security vulnerability. https://www.youtube.com/watch?v=fBHuccOoxpo
4. C++20 format or fmt are also very slow. https://youtu.be/zozo8b7-nsw?si=EKeHO2cWwY0JPRRY
5. operator overloading is bad for sure, but the solution isn't to use format string. it is to use a library that is better designed without operator overloadings or other pitfalls.
6. io manipulators should be replaced with a static one, not a stateful manipulator.
Can you have a look at fast_io?
https://github.com/cppfastio/fast_io
7. I am Chinese and no Chinese I knew have issues with your example.

I appreciate your message on iostream being broken, but fmt or format are not good either. format string vulnerabilities have been huge security hazards.

**Comment by trcrsired** [comment]
![image](https://github.com/depp/vadpcm/assets/100043421/7811a1cb-a549-4939-808a-d77012b0cac0)

**Comment by depp** [comment]
Do not misuse the GitHub issue system as a way to send me personal messages.
